export const tokens = {
  colors: {
    bgPrimary: 'var(--iw-bg-primary)',
    bgSecondary: 'var(--iw-bg-secondary)',
    bgCard: 'var(--iw-bg-card)',
    bgGlass: 'var(--iw-bg-glass)',
    bgGlassHover: 'var(--iw-bg-glass-hover)',
    bgGlassSubtle: 'var(--iw-bg-glass-subtle)',
    bgGlassSubtleHover: 'var(--iw-bg-glass-subtle-hover)',
    borderSubtle: 'var(--iw-border-subtle)',
    borderHover: 'var(--iw-border-hover)',
    borderActive: 'var(--iw-border-active)',
    borderDivider: 'var(--iw-border-divider)',
    textPrimary: 'var(--iw-text-primary)',
    textSecondary: 'var(--iw-text-secondary)',
    textMuted: 'var(--iw-text-muted)',
    textGhost: 'var(--iw-text-ghost)',
    accentBlue: 'var(--iw-accent-blue)',
    accentBlueGlow: 'var(--iw-accent-blue-glow)',
    accentBlueSoft: 'var(--iw-accent-blue-soft)',
    accentGreen: 'var(--iw-accent-green)',
    accentGreenGlow: 'var(--iw-accent-green-glow)',
    accentGreenSoft: 'var(--iw-accent-green-soft)',
    accentRed: 'var(--iw-accent-red)',
    accentRedGlow: 'var(--iw-accent-red-glow)',
    accentAmber: 'var(--iw-accent-amber)',
    accentAmberGlow: 'var(--iw-accent-amber-glow)',
    statusLive: 'var(--iw-status-live)',
    statusLiveGlow: 'var(--iw-status-live-glow)',
  },
  shadow: {
    card: '0 1px 3px rgba(0,0,0,0.24), 0 0 1px rgba(255,255,255,0.04)',
    cardHover: '0 4px 20px rgba(0,0,0,0.35), 0 1px 4px rgba(0,0,0,0.2), 0 0 1px rgba(255,255,255,0.06)',
    shell: '0 12px 48px rgba(0,0,0,0.55), 0 4px 16px rgba(0,0,0,0.35), 0 1px 4px rgba(0,0,0,0.25), 0 0 0 1px rgba(255,255,255,0.06), inset 0 1px 0 rgba(255,255,255,0.04)',
    float: '0 8px 32px rgba(0,0,0,0.5), 0 2px 8px rgba(0,0,0,0.3)',
  },
  radius: {
    xs: 4,
    sm: 6,
    md: 10,
    lg: 14,
    xl: 18,
    '2xl': 22,
  },
  blur: {
    glass: 28,
    heavy: 48,
  },
  spacing: {
    xs: 4,
    sm: 6,
    md: 10,
    lg: 14,
    xl: 18,
  },
  animation: {
    durationFast: 0.15,
    durationNormal: 0.25,
    durationSlow: 0.35,
    easeOutExpo: [0.16, 1, 0.3, 1] as const,
    easeOutSmooth: [0.22, 0.68, 0, 1] as const,
    easeInOutSmooth: [0.4, 0, 0.2, 1] as const,
    spring: { type: 'spring' as const, stiffness: 320, damping: 32 },
    springGentle: { type: 'spring' as const, stiffness: 220, damping: 26 },
    springSnappy: { type: 'spring' as const, stiffness: 440, damping: 38 },
    springBouncy: { type: 'spring' as const, stiffness: 500, damping: 30 },
  },
} as const
